<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rblive</string>
	</array>
	<key>keyEquivalent</key>
	<string>~@R</string>
	<key>name</key>
	<string>Ruby Livecode</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruby.livecode</string>
	<key>uuid</key>
	<string>5005ED25-4281-4325-B6B6-35C4A219200A</string>
</dict>
</plist>
